required = ["github.com/gogo/googleapis/google/rpc",
            "github.com/gogo/googleapis/google/api",
            "github.com/gogo/protobuf/types",
            "github.com/golang-collections/go-datastructures",
            "google.golang.org/grpc"]

[[constraint]]
  branch = "master"
  name = "github.com/buger/jsonparser"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
